spring.application.name=keystone-backend

spring.datasource.url=jdbc:postgresql://ep-jolly-heart-aw927uj4.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DKuTiQodz7s3
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}

server.port=8080

jwt.secret=MySuperSecretKeyForKeystoneBackendApplication2026SecureKey123456
jwt.expiration=86400000